### ISSUE TITLE
Hook `before_rabbithole_stores_documents` breaks other plugins

### ISSUE THREAD

**Issue by pieroit** [AlessandroSpallina/ccat-dietician#1]
Since this plugin's hook `before_rabbithole_stores_documents` [always returns an empty list](https://github.com/AlessandroSpallina/ccat-dietician/blob/43bed12247f341ee71786c8b70b522b0a502818b/dietician.py#L70), it does not play well with other plugins that may want to operate on the docs about to be stored. 

An option is to just remove duplicate texts from the `docs` list or access memory and clean from other hooks

Thanks :)

**Comment by AlessandroSpallina** [comment]
Fixed in v0.2
